// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: protocol/service.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Server_Communicate_FullMethodName       = "/service.Server/Communicate"
	Server_FriendListener_FullMethodName    = "/service.Server/FriendListener"
	Server_GetAllUserInfo_FullMethodName    = "/service.Server/GetAllUserInfo"
	Server_StreamAllUserInfo_FullMethodName = "/service.Server/StreamAllUserInfo"
)

// ServerClient is the client API for Server service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServerClient interface {
	// Handles client ping/pong communication
	Communicate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, Ping], error)
	// Handles friend listener for online status
	// rpc FriendListener (stream FriendListenerMessage) returns (stream FriendStatusUpdate);
	FriendListener(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FriendListenerRequest, FriendListenerResponse], error)
	// New function to fetch all users from Redis
	GetAllUserInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UserList, error)
	// New streaming function to send real-time Redis user info list
	StreamAllUserInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UserList], error)
}

type serverClient struct {
	cc grpc.ClientConnInterface
}

func NewServerClient(cc grpc.ClientConnInterface) ServerClient {
	return &serverClient{cc}
}

func (c *serverClient) Communicate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, Ping], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Server_ServiceDesc.Streams[0], Server_Communicate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMessage, Ping]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Server_CommunicateClient = grpc.BidiStreamingClient[ClientMessage, Ping]

func (c *serverClient) FriendListener(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FriendListenerRequest, FriendListenerResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Server_ServiceDesc.Streams[1], Server_FriendListener_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FriendListenerRequest, FriendListenerResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Server_FriendListenerClient = grpc.BidiStreamingClient[FriendListenerRequest, FriendListenerResponse]

func (c *serverClient) GetAllUserInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UserList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserList)
	err := c.cc.Invoke(ctx, Server_GetAllUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) StreamAllUserInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UserList], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Server_ServiceDesc.Streams[2], Server_StreamAllUserInfo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, UserList]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Server_StreamAllUserInfoClient = grpc.ServerStreamingClient[UserList]

// ServerServer is the server API for Server service.
// All implementations must embed UnimplementedServerServer
// for forward compatibility.
type ServerServer interface {
	// Handles client ping/pong communication
	Communicate(grpc.BidiStreamingServer[ClientMessage, Ping]) error
	// Handles friend listener for online status
	// rpc FriendListener (stream FriendListenerMessage) returns (stream FriendStatusUpdate);
	FriendListener(grpc.BidiStreamingServer[FriendListenerRequest, FriendListenerResponse]) error
	// New function to fetch all users from Redis
	GetAllUserInfo(context.Context, *Empty) (*UserList, error)
	// New streaming function to send real-time Redis user info list
	StreamAllUserInfo(*Empty, grpc.ServerStreamingServer[UserList]) error
	mustEmbedUnimplementedServerServer()
}

// UnimplementedServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServerServer struct{}

func (UnimplementedServerServer) Communicate(grpc.BidiStreamingServer[ClientMessage, Ping]) error {
	return status.Errorf(codes.Unimplemented, "method Communicate not implemented")
}
func (UnimplementedServerServer) FriendListener(grpc.BidiStreamingServer[FriendListenerRequest, FriendListenerResponse]) error {
	return status.Errorf(codes.Unimplemented, "method FriendListener not implemented")
}
func (UnimplementedServerServer) GetAllUserInfo(context.Context, *Empty) (*UserList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllUserInfo not implemented")
}
func (UnimplementedServerServer) StreamAllUserInfo(*Empty, grpc.ServerStreamingServer[UserList]) error {
	return status.Errorf(codes.Unimplemented, "method StreamAllUserInfo not implemented")
}
func (UnimplementedServerServer) mustEmbedUnimplementedServerServer() {}
func (UnimplementedServerServer) testEmbeddedByValue()                {}

// UnsafeServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServerServer will
// result in compilation errors.
type UnsafeServerServer interface {
	mustEmbedUnimplementedServerServer()
}

func RegisterServerServer(s grpc.ServiceRegistrar, srv ServerServer) {
	// If the following call pancis, it indicates UnimplementedServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Server_ServiceDesc, srv)
}

func _Server_Communicate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ServerServer).Communicate(&grpc.GenericServerStream[ClientMessage, Ping]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Server_CommunicateServer = grpc.BidiStreamingServer[ClientMessage, Ping]

func _Server_FriendListener_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ServerServer).FriendListener(&grpc.GenericServerStream[FriendListenerRequest, FriendListenerResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Server_FriendListenerServer = grpc.BidiStreamingServer[FriendListenerRequest, FriendListenerResponse]

func _Server_GetAllUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).GetAllUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Server_GetAllUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).GetAllUserInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_StreamAllUserInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServerServer).StreamAllUserInfo(m, &grpc.GenericServerStream[Empty, UserList]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Server_StreamAllUserInfoServer = grpc.ServerStreamingServer[UserList]

// Server_ServiceDesc is the grpc.ServiceDesc for Server service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Server_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.Server",
	HandlerType: (*ServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllUserInfo",
			Handler:    _Server_GetAllUserInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Communicate",
			Handler:       _Server_Communicate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "FriendListener",
			Handler:       _Server_FriendListener_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamAllUserInfo",
			Handler:       _Server_StreamAllUserInfo_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protocol/service.proto",
}
